### ISSUE TITLE
Allow users to reset their own passwords with First Use Authenticator

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/outreachy#2]
[FirstUseAuthenticator](https://github.com/yuvipanda/jupyterhub-firstuseauthenticator) is a JupyterHub authenticator where the first password a user uses is considered their password of record. This works great for simple use cases, but is problematic when users need to reset their own password.

For this task, make a GitHub Pull Request to the [FirstUseAuthenticator](https://github.com/yuvipanda/jupyterhub-firstuseauthenticator) github repo with a feature that lets users change their own passwords:

1. Providing a web page at a custom URL - `/auth/change-password`. Users need to manually go to this URL to change their passwords.
2. A text box for users to enter new password. Another for them to type it again so it can be confirmed.
3. A 'confirm change' button that when pressed, sets it as the new user password

Helpful links:

1. Tornado tutorial: http://www.tornadoweb.org/en/stable/
2. https://jupyterhub.readthedocs.io/en/stable/reference/authenticators.html#how-to-write-a-custom-authenticator has information on how authenticators work
3. https://github.com/yuvipanda/jupyterhub-simplespawner is a useful spawner class to test authenticator implementations
4. https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/globus.py#L223 example of adding custom web pages to authenticators

Getting Help:

Comment on this issue, or ping us [on Gitter](https://gitter.im/jupyterhub/jupyterhub) for help!

**Comment by leportella** [comment]
Hi! I am an outreachy applicant and I would like to work on this :)

**Comment by minrk** [comment]
@leportella great! Feel free to ask guidance questions here or on gitter.

**Comment by minrk** [comment]
That sounds like great progress!

You are right that modifying jupyterhub/jupyterhub probably isn't the right approach, but the principles ought to be the same, it's just a bit of a question about where the code lands. In this case, it should all live in `firstuseauthenticator`.

> Where this template should be stored?

I would put it in `firstuseauthenticator/templates/reset.html` (`templates` would be a sibling of `firstuseauthenticator.py`)

Jinja has the ability to load templates from multiple sources. One way to do that is to register your path with the jinja environment. We can then *add* this by creating a ChoiceLoader, which takes one or more Loaders and iterates through them until it finds a match:

```python
import os
from jinja2 import ChoiceLoader, FileSystemLoader

# a 'templates' directory next to the current file
TEMPLATE_DIR = os.path.join(os.path.dirname(__file__), "templates")


class ResetPasswordHandler(BaseHandler):
    """Render the reset password page."""

    # flag to indicate whether the template path has been loaded
    _loaded = False

    def _register_template_path(self):
        if ResetPasswordHandler._loaded:
            # already loaded, do nothing
            return
        # create a FileSystemLoader that will find our template
        self.log.debug("Adding %s to template path", TEMPLATE_DIR)
        my_loader = FileSystemLoader([TEMPLATE_DIR])

        # register our loader with the jinja environment
        # *in addition to* the existing loaders
        env = self.settings['jinja2_env']
        previous_loader = env.loader
        env.loader = ChoiceLoader([previous_loader, my_loader])

        # signal that this modification should only occur once
        ResetPasswordHandler._loaded = True


    @web.authenticated
    async def get(self):
        # make sure our template is registered
        self._register_template_path()
        ...
```

> I'm not quite sure how can I pass information from the input that comes from the handler form to the authenticator.

This would generally be in the form of a POST request coming from a `<form>`. There's an example in JupyterHub on the login page, where the form [is defined here](https://github.com/jupyterhub/jupyterhub/blob/0.9.4/share/jupyterhub/templates/login.html#L22-L67) and the resulting POST request is handled [by adding a `def post` method here](https://github.com/jupyterhub/jupyterhub/blob/0.9.4/jupyterhub/handlers/login.py#L74-L93). The URL for the post is defined by the `action` attribute [here](https://github.com/jupyterhub/jupyterhub/blob/0.9.4/share/jupyterhub/templates/login.html#L22). If you don't specify `action` at all, then it will default to the current page, which is probably what you want (define `get` and `post` methods both on the same Handler class).

> I'm not sure if the reset_password method is best to stay in the authenticator or if it can remain on the handler.

In practice, it usually doesn't matter too much, but as a general guideline in JupyterHub and web applications in general, I like to get as much logic implemented in portable classes (Authenticator, Spawner, etc.) so that they can be used and tested without a web application. Then the only job of the Handler is to expose the APIs on those objects via the web.

**Comment by leportella** [comment]
@minrk thank you for your comments. They were extremely helpful!

I created a [Pull Request](https://github.com/jupyterhub/firstuseauthenticator/pull/8) but @yuvipanda comments puts a link for testing the Authenticator. Since no tests were available, I created a PR without it and came here to ask for help on this subject.  Should this be done with tests? Should I created tests for everything?

Again, thank you both for your help :)

**Comment by minrk** [comment]
@leportella If you'd like to take a stab at adding tests, that would be awesome, but since we haven't set up the initial testing on that repo, I don't think we can reasonably ask you to do that right now. I've started the basics in https://github.com/jupyterhub/firstuseauthenticator/pull/9, which should make it doable to add a test for the `.reset_password` method. Testing the handler might be more tricky, since you'll need to do either extensive mocking or instantiate JupyterHub in the tests.

A basic test for

**Comment by leportella** [comment]
I will add it to the docs as well :) I also saw an issue about name sanitizing that I could do, as well, but I would like your thoughts on that :)

**Comment by leportella** [comment]
@yuvipanda I added a question on FAQ to serve as docs. If you prefer to do it in some other way, please let me know.

**Comment by yuvipanda** [comment]
Awesome, @leportella! I'll call this task as done!

Congratulations :)
